Repository AYUSHAGARWAL1901/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#3 Add ecapture
  captureImg.py
  main.py
Labels: hacktoberfest

#4 Update main.py
  main.py
Labels: good first issue, hacktoberfest

#5 read me updated
  README.md
Labels: documentation, hacktoberfest

#6 Create a log out else if
  main.py
Labels: bug, good first issue, hacktoberfest

#8 Changes answer function , previous changes done
  main.py
Labels: enhancement, hacktoberfest

#9 create decision tree
  decision_tree.py
Labels: enhancement, hacktoberfest

#10 tic_tac_toe.py
  tic_tac_toe.py
Labels: enhancement, hacktoberfest
